// Scalar ships no Swedish; its text is merged over the English, so every label a reader can meet is set here.
// The labels of features that are switched off (agent, MCP, developer tools, the getting-started page) are not.
export const translations = {
  common: {
    description: 'Beskrivning',
    httpMethod: 'HTTP-metod',
    path: 'Sökväg',
    copyDefault: 'Kopiera standardvärdet',
    copyExample: 'Kopiera exemplet',
    streamItem: 'Ström',
  },
  search: {
    label: 'Sök',
    inputLabel: 'Skriv en sökfråga',
    open: 'Öppna sökningen',
    placeholder: 'Sök …',
    clear: 'Rensa sökningen',
    noResults: 'Inga träffar',
    keyboardShortcut: 'Kortkommando:',
    command: 'Kommando',
    control: 'Ctrl',
    results: 'Sökresultat i referensen',
    navigate: 'Bläddra',
    select: 'Välj',
    instructions: 'Bläddra med pil upp och pil ner, välj med Retur, skriv för att filtrera',
    entryHeading: 'Rubrik',
    entryOperation: 'Anrop',
    entryTag: 'Grupp',
    entryTagGroup: 'Grupp',
    entryWebhook: 'Webhook',
  },
  footer: {
    poweredByScalar: 'Drivs av Scalar',
  },
  navigation: {
    introduction: 'Inledning',
    closeGroup: 'Stäng gruppen',
    closeMenu: 'Stäng menyn',
    openGroup: 'Öppna gruppen',
    openMenu: 'Öppna menyn',
    operations: 'Anrop',
    endpoints: 'Anrop i {name}',
    showAllEndpoints: 'Visa alla anrop i {name}',
    sidebarFor: 'Sidomeny för {name}',
    mainContent: 'API-dokumentation för {name}',
    collapsed: 'Hopfälld',
    webhooks: 'Webhooks',
    channels: 'Kanaler',
  },
  server: { label: 'Server', select: 'Välj en server' },
  info: { termsOfService: 'Användarvillkor' },
  clientLibraries: {
    heading: 'Klientbibliotek',
    more: 'Fler',
    selectAll: 'Välj bland alla klienter',
    searchLabel: 'Sök klienter',
    changeClient: 'Byt språk för kodexemplet',
  },
  operation: {
    codeSampleUnavailable: 'Det finns inget kodexempel för det här exemplet.',
    codeSample: 'Kodexempel',
    body: 'Innehåll',
    cookies: 'Cookies',
    headers: 'Headers',
    pathParameters: 'Parametrar i sökvägen',
    queryParameters: 'Parametrar i adressen',
    requestBody: 'Innehåll i anropet',
    responses: 'Svar',
    testRequest: 'Testa anropet',
    webhook: 'Webhook',
    selectedContentType: 'Vald innehållstyp',
    callbacks: 'Återanrop',
  },
  response: {
    xmlGenerationLimit: 'XML-exemplet är för stort för att genereras. Ange ett färdigt XML-exempel för att visa hela innehållet.',
    xmlGenerationFailed: 'Det gick inte att skapa ett XML-exempel: {message}',
    exampleResponses: 'Exempel på svar',
    noBody: 'Inget innehåll',
    showSchema: 'Visa schemat',
    status: 'Status',
  },
  schema: {
    noAllowedValues: 'Inget värde uppfyller villkoret för uppräkningen.',
    example: 'Exempel',
    examples: 'Exempel',
    default: 'Standard',
    schema: 'Schema',
    emptyObject: 'Tomt objekt',
    showAdditionalProperties: 'Visa fler egenskaper',
    forName: 'för {name}',
    showSchemaDetails: 'Visa detaljer om schemat',
    oneOf: 'Ett av',
    anyOf: 'Något av',
    allOf: 'Alla av',
    not: 'Inte',
    unknownType: 'okänd typ',
    propertyCount: 'Egenskaper: {count}',
    headerCount: 'Headers: {count}',
    recursiveReference: 'Återkommande referens till {name}',
    recursive: 'återkommande',
    additionalProperties: 'fler egenskaper',
    const: 'konstant',
    deprecated: 'föråldrad',
    discriminator: 'Diskriminator',
    enum: 'uppräkning',
    format: 'Format',
    greaterThan: 'större än',
    keys: 'nycklar',
    lessThan: 'mindre än',
    max: 'högst',
    min: 'minst',
    maxLength: 'längst',
    minLength: 'kortast',
    multipleOf: 'multipel av',
    nullable: 'kan vara null',
    propertyNames: 'egenskapsnamn',
    pattern: 'Mönster',
    copyPattern: 'Kopiera mönstret',
    readOnly: 'skrivskyddad',
    required: 'obligatorisk',
    hideValues: 'Dölj värdena',
    showAllValues: 'Visa alla värden',
    type: 'Typ',
    unique: 'unik',
    values: 'värden',
    writeOnly: 'bara för skrivning',
  },
  download: {
    openapi: 'Ladda ned OpenAPI-filen',
    asyncapi: 'Ladda ned AsyncAPI-filen',
    asFormat: '{label} som {format}',
  },
  models: { label: 'Modeller' },
  actions: {
    copyAsMarkdown: 'Kopiera som Markdown',
    copied: 'Kopierat',
    copyMarkdownFailed: 'Det gick inte att kopiera Markdown',
    copyLink: 'Kopiera länken',
    copyLinkTo: 'Kopiera länken till {name}',
    copyToClipboard: 'Kopiera länken till urklipp',
    copyEndpointUrl: 'Kopiera adressen till anropet',
    showMore: 'Visa mer',
  },
  authentication: {
    detailsRequired: 'Kräver inloggning',
    detailsOptional: 'Inloggning är valfri',
    apiKey: 'API-nyckel',
    mutualTLS: 'Ömsesidig TLS',
    apiKeyCookie: 'Skicka API-nyckeln i cookien ”{name}”.',
    apiKeyHeader: 'Skicka API-nyckeln i headern ”{name}”.',
    apiKeyQuery: 'Skicka API-nyckeln i parametern ”{name}”.',
    title: 'Inloggning',
    accepts: 'Godtar',
    allOf: 'alla av:',
    authentication: 'inloggning',
    optional: 'Inloggning valfri',
    oneOf: 'en av:',
    required: 'Inloggning krävs',
    requires: 'Kräver',
    scopes: 'OAuth-behörigheter',
  },
}
