import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

const SCRIPT = join(__dirname, "..", "..", "scripts", "verify-candidate.mjs");
const run = (...args: string[]) => spawnSync(process.execPath, [SCRIPT, ...args], { encoding: "utf8" });

test("the candidate CLI isolates working code, new tests and dependencies, excludes ignored files, and detects later changes", (t) => {
  const root = mkdtempSync(join(tmpdir(), "stt-candidate-test-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const source = join(root, "source");
  const write = (name: string, content: string) => {
    const file = join(source, name);
    mkdirSync(join(file, ".."), { recursive: true });
    writeFileSync(file, content);
  };
  write(".gitignore", "node_modules/\n.env\n");
  write("frontend/lib/app.ts", "export const label = 'old';");
  write("frontend/package-lock.json", "{}");
  write("backend/app/main.py", "VERSION = 1");
  write(".github/workflows/ci.yml", "jobs: {}");
  spawnSync("git", ["init", "-q", source]);
  assert.equal(spawnSync("git", ["-C", source, "add", "."]).status, 0);
  write("frontend/lib/app.ts", "export const label = 'current';");
  write("frontend/tests/e2e/new.spec.ts", "new test");
  write("frontend/node_modules/fixture/index.js", "dependency");
  symlinkSync(join(source, "frontend/node_modules"), join(source, "backend/.venv"), "dir");
  write(".env", "private");
  const preparing = run("--source", source, "--prepare-only", "--checks", "dev,real", "--grep", "one focus frame");
  assert.equal(preparing.status, 0, preparing.stderr);
  const { candidate } = JSON.parse(preparing.stdout) as { candidate: string };
  // The fixture owns these temporary directories, including their read-only files.
  t.after(() => rmSync(candidate, { recursive: true, force: true }));
  assert.deepEqual(JSON.parse(readFileSync(join(candidate, "candidate.json"), "utf8")).selection.checks, ["dev", "real"]);
  assert.equal(readFileSync(join(candidate, "frontend/lib/app.ts"), "utf8"), "export const label = 'current';");
  assert.equal(readFileSync(join(candidate, "frontend/tests/e2e/new.spec.ts"), "utf8"), "new test");
  assert.equal(existsSync(join(candidate, ".env")), false);
  assert.equal(existsSync(join(candidate, "backend/.venv")), false);
  assert.equal(readFileSync(join(candidate, ".github/workflows/ci.yml"), "utf8"), "jobs: {}", "backend checks also read repository CI contracts");
  assert.equal(statSync(join(candidate, "frontend/lib/app.ts")).mode & 0o222, 0);
  write("frontend/lib/app.ts", "changed while testing");
  write("frontend/node_modules/fixture/index.js", "changed dependency");
  assert.equal(readFileSync(join(candidate, "frontend/node_modules/fixture/index.js"), "utf8"), "dependency");
  assert.equal(run("--verify", candidate).status, 0, "edits to the workspace do not invalidate the candidate");
  const captured = join(candidate, "frontend/tests/e2e/new.spec.ts");
  chmodSync(captured, 0o644);
  writeFileSync(captured, "changed candidate");
  const changed = run("--verify", candidate);
  assert.notEqual(changed.status, 0);
  assert.match(changed.stderr, /frontend\/tests\/e2e\/new\.spec\.ts/);
  writeFileSync(captured, "new test");
  chmodSync(captured, 0o444);
  const added = join(candidate, "frontend/tests/e2e/added.spec.ts");
  writeFileSync(added, "added during the run");
  const extra = run("--verify", candidate);
  assert.notEqual(extra.status, 0);
  assert.match(extra.stderr, /frontend\/tests\/e2e\/added\.spec\.ts/);
  rmSync(join(source, "frontend/node_modules"), { recursive: true, force: true });
  const failedCapture = run("--source", source, "--prepare-only");
  assert.notEqual(failedCapture.status, 0);
  const failed = /candidate: (.+)/.exec(failedCapture.stderr)?.[1];
  assert.ok(failed, "a failed capture leaves its location and reason");
  t.after(() => rmSync(failed, { recursive: true, force: true }));
  assert.equal(JSON.parse(readFileSync(join(failed, "candidate.json"), "utf8")).status, "capture_failed");
});
