/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: kit/theme/eneo.theme.ts
 * Command: astryx theme build kit/theme/eneo.theme.ts --out kit/theme/built/eneo.css
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const eneoTheme: DefinedTheme;
